### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zqx951102** [microsoft/Relation-Aware-Global-Attention-Networks#25]
D:\PyCode\Detection-PyTorch-Notebook-master\venv\Scripts\python.exe D:/PyCode/PersonReID/Relation-Aware-Global-Attention-Networks/main_imgreid.py
Traceback (most recent call last):
  File "D:/PyCode/PersonReID/Relation-Aware-Global-Attention-Networks/main_imgreid.py", line 299, in <module>
    main(parser.parse_args())
  File "D:/PyCode/PersonReID/Relation-Aware-Global-Attention-Networks/main_imgreid.py", line 138, in main
    args.combine_trainval, args.rerank)
  File "D:/PyCode/PersonReID/Relation-Aware-Global-Attention-Networks/main_imgreid.py", line 89, in get_data
    num_classes = dataset.num_train_pids
UnboundLocalError: local variable 'dataset' referenced before assignment

Process finished with exit code 1

**Comment by zqx951102** [comment]
运行main这个文件时候，报错，有没有出现同样问题的小伙伴啊  咋解决的

**Comment by zqx951102** [comment]
请问 你知道咋解决的吗 我到现在也是不知道咋搞了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Relation-Aware-Global-Attention-Networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月16日(星期六) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25)





 
我也是同样的报错
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqx951102** [comment]
zqx951102 &nbsp;微信 &nbsp;加一下 兄弟 &nbsp;有空继续探讨 &nbsp; &nbsp;我先准备下周组会，加一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Relation-Aware-Global-Attention-Networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月16日(星期六) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25)





 没有呢，困扰了好多天了，网上说是全局变量的问题，改完之后还是报错。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "microsoft/Relation-Aware-Global-Attention-Networks"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年10月16日(星期六) 中午11:11 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25) 
 
 
 
 
 
  请问 你知道咋解决的吗 我到现在也是不知道咋搞了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "microsoft/Relation-Aware-Global-Attention-Networks"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年10月16日(星期六) 中午11:08  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25)  
   
   
   
   
   
     
  我也是同样的报错  
     
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mountain-shui** [comment]
你们的训练参数写错了吧
`-a resnet50_rga
-b 64
-d cuhk03labeled
-j 0
--opt adam
--dropout 0
--combine-trainval
--seed 16
--num_gpu 1
--epochs 600
--features 2048
--start_save 300
--branch_name rgasc
--data-dir ./data
--logs-dir ./logs/RGA-SC/cuhk03labeled_b64f2048`

其中   -d cuhk03labeled  对应着D:/PyCode/PersonReID/Relation-Aware-Global-Attention-Networks/main_imgreid.py", line 89 左右有一行代码 dataset == 'cuhk03labeled'

**Comment by dcmi2020** [comment]
> zqx951102 &nbsp;微信 &nbsp;加一下 兄弟 &nbsp;有空继续探讨 &nbsp; &nbsp;我先准备下周组会，加一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/Relation-Aware-Global-Attention-Networks" ***@***.***&gt;; 发送时间:&nbsp;2021年10月16日(星期六) 中午11:13 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25) 没有呢，困扰了好多天了，网上说是全局变量的问题，改完之后还是报错。
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "microsoft/Relation-Aware-Global-Attention-Networks" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2021年10月16日(星期六) 中午11:11 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25) 请问 你知道咋解决的吗 我到现在也是不知道咋搞了
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "microsoft/Relation-Aware-Global-Attention-Networks" ***@***.***&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2021年10月16日(星期六) 中午11:08 ***@***.***&amp;amp;gt;; ***@***.******@***.***&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [microsoft/Relation-Aware-Global-Attention-Networks] 报错 (#25) 我也是同样的报错 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

请问解决了吗？
